### ISSUE TITLE
USER STORY: Planning

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#1]
EPIC: Preparation & Planning

As a **side owner**, I want to plan the project carefully, so that the web app meets MVP.

**ACCEPTANCE CRITERIA**
- [x] A GitHub project is created with all user stories and corresponding prioritization.
- [x] A first mentor session was conducted.

** TASKS**
- [x] Create Project, Epics, User Stories, Labels, Iteration 1
- [x] Prioritize
- [x] Organized and prepare for the first mentor session
- [x] Create basic structure of README
