### ISSUE TITLE
USER STORY: Extended Homepage

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#10]
EPIC: General Information

As a first user, I want to read general information about the procedure.

**ACCEPTANCE CRITERIA**
- [x] Homepage contains How it works Section

** TASKS**
- [x] Add How it works template
- [x] Add view and url
- [x] Documentation
- [x] Testing
