### ISSUE TITLE
USER STORY: Book Key Generator

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#12]
EPIC: Book registration

As a developer, I want to generate a unique code so that the book can be easily identified.

**ACCEPTANCE CRITERIA**
- [x] There is a logic which generates a unique and secured code for the book.
- [x] There is a page which displays a unique code after a book is registered.

**TASKS**
- [x] Add a key into the book model
- [x] Create a function
- [x] Create view
- [x] Add url
- [x] Testing
- [x] Documenting

**Comment by brodsa** [comment]
The solution of the user story was a bit unclear at the beginning.  Therefore, some moddification has been made in tasks and acceptance criteria.
