### ISSUE TITLE
USER STORY: Book registration

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#13]
EPIC: Book Registration

As a user, I want to add a new book, so that it can start its journey.

**ACCEPTANCE CRITERIA**
- [x] The registered and logged in user can add new book
- [x] The unregistered user cannot register a book.

**TASKS**
- [x] Create and style New Book template
- [x] Create View (User input validation)
- [x] Create url
- [x] Add link
- [x] Documentation
- [x] Testing

**Comment by brodsa** [comment]
- [ ] Before the book is registered, there is a review of provided information. will be done in next iterations
