### ISSUE TITLE
USER STORY: Books overview

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#14]
EPIC: Registered User

As a user, I want to see all books which are registered by me or others.

**ACCEPTANCE CRITERIA**
- [x] There is Books Section containing all registered books. Each book is displayed as card.
- [x] The all books can see only logged in users, not registered users can view only some.

** TASKS**
- [x] Create and style Book template
- [x] Create view
- [x] Create url
- [x] Add link
- [x] Document
- [x] Testing
- [ ]

**Comment by brodsa** [comment]
Edit Acceptance criteria regarding the summary statistics displayed in cards. The data model for this is not yet implemented, see #20. The criteria was change to who can view the full content of the Latest Books Pages.
