### ISSUE TITLE
USER STORY: Edit Book

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#16]
EPIC: Book registration

As a user, I want to have the possibility to edit the provided information about my books anytime, so that I can have a full control of what I published.

**ACCEPTANCE CRITERIA**
- [x] Only registered users can edit the information about his/her registered book. Nobody else can do it.
- [x] There is a button on a book card which enables to edit the information.

** TASKS**
- [x] Create Edit Book template
- [x] Create view
- [x] Create url
- [x] Add link and button
- [x] Documentation
- [x] Testing
