### ISSUE TITLE
USER STORY: Deleting Book

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#17]
EPIC: Book registration

As a user, I want to have the possibility to delete the registered book, so that I can stop the book journey anytime I want

**ACCEPTANCE CRITERIA**
- [x] Only registered users can delete his/her registered book. Nobody else can do it
- [x] There is a button on a book card which enables to delete the information

** ASKS**
- [x] Create Delete Book template
- [x] Create view
- [x] Create url
- [x] Add link and button
- [x] Documentation
- [x] Testing
- [ ]
