### ISSUE TITLE
USER STORY: Initial Setup

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#2]
EPIC: Preparation & Planning

As a side owner, I want to setup my workspace so that I can develop and deploy the web app easily.

**ACCEPTANCE CRITERIA**
- [x] The initial packages are installed to run Django project.
- [x] The web app was deployed on Heroku with SQL Elephant as production database.

** TASKS**
- [x] Installation of all packages
- [x] Create and setup Django app
- [x] Setup Elephant SQL
- [x] Set up Environmental variables
- [x] Setup Heroku
- [x] First deployment
- [x] Documentation
