### ISSUE TITLE
USER STORY: Books with owner status

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#25]
EPIC:Registered User

As a user, I want to easily see my registered, contributed and all books, so that I have a good overview

**ACCEPTANCE CRITERIA**
- [x] There are buttons in the books page which can automatically filter all books, registered books, contributed book. 
- [x] This page can only see logged in users.

** TASKS**
- [x] Create buttons
- [x] Create filter function
