### ISSUE TITLE
USER STORY: Contact Link

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#30]
EPIC: Contact

As a user, I want to have a possibility to contact a developer, so that I can provide my feedback

**ACCEPTANCE CRITERIA**
- [x] Any user can click on contact link, either in menu or footer.
- [x] The link will open contact form

** TASKS**
- [x] Create Model
- [x] Add Model in Admin Panel
- [x] Create Form
- [x] Add URL and Links
- [x] Testing
- [x] Document
