### ISSUE TITLE
USER STORY: Search Book

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#35]
EPIC: Registered User

As a user, I want to search on the page a book according to the book name.

**ACCEPTANCE CRITERIA**
- [x] There is search field where the user can search books based on book name.

** TASKS**
- [x] Create search input
- [x] Create a search function
