### ISSUE TITLE
USER STORY: Book rating

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#36]
EPIC: Registered User

As a user, I want to rate the book, so that I can give others a better impression about the book.

**ACCEPTANCE CRITERIA**
- [ ] The user can give 1-3 stars to each book. The overall rating is displayed on the card book as the average.

** TASKS**
- [ ] Create and style stars
- [ ] Build the logic in backend
