### ISSUE TITLE
USER STORY: Edit User

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#38]
EPIC: User Registration

As a user, I want to edit my user account information, so that I can change some of it.

**ACCEPTANCE CRITERIA**
- [ ] The registered and logged in user can edit the profile information. 
- [ ] The unregistered/unlogged user cannot do it.

** TASKS**
- [ ] Create Edit Profile template
- [ ] Create view
- [ ] Create url
- [ ] Add link
- [ ] Documentation
- [ ] Testing
