### ISSUE TITLE
USER STORY: Navigation Menu

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#4]
EPIC: General Information

As a user, I want to easily navigate through the web pages, so that I can find the information fast and intuitively.

**ACCEPTANCE CRITERIA**
- [x] The webpage contains navigation menu.
- [x] The navigation menu is responsive, i.e. hamburger menu for mobile devices

** TASKS**
- [x] Create and style navigation menu
- [x] Add Links: Member Area, How it works, About, Contact
- [x] Add Logo
- [x] Documentation
- [x] Testing

**Comment by brodsa** [comment]
The links will be added when all pages are created, i.e. part of other user stories.
