### ISSUE TITLE
USER STORY: Final Deployment

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#40]
EPIC: Deployment

As a developer, I wan to the final page is deployed, so that user can use all implemented features 

**ACCEPTANCE CRITERIA**
- [x] The final webpage was deployed on Heroku
- [x] There are no comments in code.

** TASKS**
- [x] Final deployment
- [x] Delete all comments
