### ISSUE TITLE
USER STORY: Form Validation

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#41]
EPIC: Book registration

As a developer, I want to validate the user input, so that the inputs for database are correct and the page is not broken

**ACCEPTANCE CRITERIA**
- [x] The validations forms are title, year, description.
- [x] The user is inform about invalid input

**TASKS**
- [x] Add input validation into form.py
