### ISSUE TITLE
USER STORY: Cities

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#48]
EPIC: Book Contribution

As a want to find my city in the Contribution Form so that I can fill it.

**ACCEPTANCE CRITERIA**
- [x] In the dropdown, there is a large number of cities.
- [x] There is a prefilled table which can be manage via admin panel

**TASKS**
- [x] Find list of European cities
- [x] Connect the list with the Contribution Form.
