### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#5]
EPIC: General Information

As a user, I want to know the social media links, so that I can follow the latest update

**ACCEPTANCE CRITERIA**
- [x] The webpage contains footer with the links to social media

**TASKS**
- [x] Create and style footer
- [x] Add social media links
- [x] Documentation
- [x] Testing
