### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#8]
EPIC: User Registration

As a user, I want to register with a username so that I can have a full access to the webpage content and be part of the community.

**ACCEPTANCE CRITERIA**
- [x] The user can registered with username via navigation menu
- [x] The registration is possible via button link in Hero Section

**TASKS**
- [x] Create and style registration template
- [x] Add Links in navigation menu and button
- [x] Documentation
- [x] Testing
