### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by brodsa** [brodsa/findMEreadME#9]
EPIC: User Registration

As a user, I want to login with my username, so that I don't have to provide my private information. 

**ACCEPTANCE CRITERIA**
- [x] User can login with username via navigation menu

**TASKS**
- [x] Create and style login template
- [x] Add links in navigation menu
- [x] Documentation
- [x] Testing

**Comment by brodsa** [comment]
View and url is not needed as it is a part of allauth package.
